#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        🚗 TRAFFIC MANAGEMENT SYSTEM - QUICK START 🚗         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "1️⃣  SETUP DATABASE"
echo "   - Open SQL Server Management Studio"
echo "   - Connect: sa / sobaannajmi"
echo "   - Run: database/database_schema.sql"
echo ""
echo "2️⃣  START BACKEND (Terminal 1)"
echo "   cd backend"
echo "   npm install"
echo "   npm run dev"
echo ""
echo "3️⃣  START FRONTEND (Terminal 2)"
echo "   cd frontend"
echo "   npm install"
echo "   npm start"
echo ""
echo "4️⃣  LOGIN"
echo "   Username: officer1"
echo "   Password: password123"
echo ""
echo "═══════════════════════════════════════════════════════════════"
